/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('./src/components/ACard/index.vue')['default']
    ADialog: typeof import('./src/components/ADialog/index.vue')['default']
    AIcon: typeof import('./src/components/AIcon/index.vue')['default']
    ASearch: typeof import('./src/components/ASearch/index.vue')['default']
    ASelectPagination: typeof import('./src/components/ASelectPagination/index.vue')['default']
    ATable: typeof import('./src/components/ATable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
